CREATE TABLE `carsmake`(`id` int NOT NULL AUTO_INCREMENT, `make` varchar(50) NULL, PRIMARY KEY (`id`));
CREATE TABLE `carsmodels`(`id` int NOT NULL AUTO_INCREMENT, `make` varchar(50) NULL, `model` varchar(50) NULL, PRIMARY KEY (`id`));
CREATE TABLE `carscars`(`category` varchar(50) NULL, `color` varchar(50) NULL, `Date Listed` date NULL, `descr` longtext NULL, `EPACity` varchar(50) NULL, `EPAHighway` varchar(50) NULL, `features` longtext NULL, `Horsepower` int NULL, `id` int NOT NULL AUTO_INCREMENT, `Make` varchar(50) NULL, `Model` varchar(50) NULL, `Phone #` varchar(50) NULL, `Picture` longblob NULL, `Price` int NULL, `UserID` varchar(50) NULL, `YearOfMake` int NULL, `zipcode` int NULL, PRIMARY KEY (`id`));
CREATE TABLE `project39_blocking`(`id` int NOT NULL AUTO_INCREMENT, `tablename` varchar(250) NOT NULL, `startdatetime` datetime NOT NULL, `confirmdatetime` datetime NOT NULL, `keys` varchar(250) NOT NULL, `sessionid` varchar(100) NOT NULL, `userid` varchar(250) NOT NULL, `action` int NULL, PRIMARY KEY (`id`));
CREATE TABLE `project41_audit`(`id` int NOT NULL AUTO_INCREMENT, `datetime` datetime NOT NULL, `ip` varchar(15) NOT NULL, `user` varchar(250) NOT NULL, `table` varchar(250) NOT NULL, `action` varchar(250) NOT NULL, `description` longtext NULL, PRIMARY KEY (`id`));
CREATE TABLE `carsusers`(`id` int NOT NULL AUTO_INCREMENT, `password` varchar(50) NULL, `username` varchar(50) NULL, PRIMARY KEY (`id`));
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `carsmake` (`id`,`make`) VALUES (9,'Audi');
INSERT INTO `carsmake` (`id`,`make`) VALUES (10,'BMW');
INSERT INTO `carsmake` (`id`,`make`) VALUES (11,'Hyundai');
INSERT INTO `carsmake` (`id`,`make`) VALUES (12,'Nissan');
INSERT INTO `carsmake` (`id`,`make`) VALUES (13,'Porsche');
INSERT INTO `carsmake` (`id`,`make`) VALUES (14,'Mazda');
INSERT INTO `carsmake` (`id`,`make`) VALUES (15,'Lexus');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (5,'Honda','Civic');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (6,'Honda','HR-V');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (7,'Honda','Pilot');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (8,'Mersedes','Cords');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (9,'Toyota','Corona');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (10,'Toyota','RAV4');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (11,'Toyota','Vitz');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (12,'Subaru','Forester');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (13,'Subaru','Impreza');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (14,'Subaru','Legacy');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (15,'Saab','9000');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (16,'Volkswagen','Golf');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (17,'Volkswagen','Passat 1.8 Turbo Sedan');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (18,'Jaguar','XJ 3.0 i V6 24V');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (19,'Audi','A3 2.0');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (20,'Audi','A4 1.8T Quattro');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (21,'Audi','A4 3.0 Cabrio');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (22,'Audi','A6 2.4');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (23,'Audi','TT');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (24,'BMW','520i');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (25,'BMW','525i');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (26,'BMW','Z4');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (27,'Hyundai','Accent');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (28,'Hyundai','Elantra');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (29,'Hyundai','Getz');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (30,'Hyundai','Sonata');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (31,'Hyundai','Tucson');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (32,'Nissan','Maxima');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (33,'Nissan','Primera');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (34,'Nissan','Terrano');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (35,'Porsche','Cayenne');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (36,'Mazda','3');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (37,'Mazda','6 2.3');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (38,'Mazda','626');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (39,'Lexus','RX 300');
INSERT INTO `carsmodels` (`id`,`make`,`model`) VALUES (40,'Honda','Civic Hybrid');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `carscars` (`category`,`color`,`Date Listed`,`descr`,`EPACity`,`EPAHighway`,`features`,`Horsepower`,`id`,`Make`,`Model`,`Phone #`,`Picture`,`Price`,`UserID`,`YearOfMake`,`zipcode`) VALUES ('Passenger Cars','Galaxy Gray Metallic','2007-04-05','Concept and name\r\rThe TT was first shown as a concept car at the 1995 Frankfurt Motor Show. The design is credited to J Mays and Freeman Thomas of Volkswagen\'s California design studio, with Martin Smith contributing to the award winning interior design. The TT name does not indicate "twin turbo" as is sometimes assumed. The car is named for the NSU TT, a small rear-engine model with a formidable racing pedigree that NSU produced in the 1960s and was based on the NSU Prinz, although the modern TT shares next to nothing with that model\'s design concepts. The NSU TT was, in turn, named for the famous Isle of Man TT (Tourist Trophy) motorcycle races.\r\rDesign\r\rThe TT\'s styling is regarded by many as a watershed moment in automobile design. From its introduction as a concept car in 1995, and as a production car in 1998, the design was regarded by many as bold, innovative, and revolutionary. While the car borrowed a few design elements from earlier vehicles, the overall design was considered by many to be truly unique. Despite its smooth-curved appeal, the design does not lead to revolutionary aerodynamics — the drag coefficient of the body is actually a relatively high 0.35 [1]. But with its distinctive, rounded bodywork, bold use of bare anodized aluminum, and a lack of defined bumpers, the TT represented a departure from much of the styling that dominated the car market at that time.\r\rThe success and popularity of the TT\'s iconic design gave many automotive designers (and manufacturers) greater latitude to experiment with bold, distinctive design. The TT\'s influence can be seen in the design elements of many vehicles released after the TT.\r\rThe TT is often regarded as the vehicle that made people take a second look at Audi. No longer just a second-tier European maker, Audi emerged as a serious competitor for the likes of BMW and Mercedes-Benz. The then-new B5-platform A4 model was a substantial improvement on its Audi 80 predecessor; these two models firmly secured Audi\'s position as a prestige marque.\r\rPerformance Models\r\rIn the 2008 Detroit Motor Show, Audi released the TTS with a 2.0TFSI engine tuned to 268 hp (200 kW). It is also rumoured that a higher end TT-RS is under development, using an all-new turbocharged 2.5L 5-cylinder engine capable of up to 350 PS (345 hp/257 kW).\r\rAwards\r\rThe TT was nominated for the North American Car of the Year award for 2000. It was also on Car and Driver magazine\'s Ten Best list for 2000 and 2001.\r\rThe second generation TT has been honored with many awards including the inaugural Drive Car of the Year, Top Gear Coupe of the Year 2006, Fifth Gear Car of the Year 2006, Autobild \'Most Beautiful Car\' and World Design Car of the Year 2007, as well as being a finalist for World Car of the Year..','','','',197,2,'Audi','TT','555-12-34',0xFFD8FFE0,57900,'admin',2000,12345);
INSERT INTO `carscars` (`category`,`color`,`Date Listed`,`descr`,`EPACity`,`EPAHighway`,`features`,`Horsepower`,`id`,`Make`,`Model`,`Phone #`,`Picture`,`Price`,`UserID`,`YearOfMake`,`zipcode`) VALUES ('Sports Cars','Nighthawk Black Pearl','2007-04-24','The 5 Series got its name by being the fifth of the "new series" cars after the V-8 and Isetta era. The preceding models were the 700, the "New Class", the "New Six" 2500/2800/Bavaria and the CS. The 5 Series was intended to replace the smaller New Class sedans, leaving the coupes as the company\'s low-end model.\r\rThe body was styled by Marcello Gandini, based on the Bertone 1970 BMW Garmisch 2002ti Geneva show car. Gandini also did the Fiat 132 and Alfa Romeo Alfetta, two other cars that have a similar design.\r\rThere have been five generations of the 5 Series to date. To differentiate between them, they are referred to by their unique chassis numbers (EXX).\r\rThe 5 Series began the BMW tradition of being named with a three-digit number. The first digit (5 in this case) represents the model, and the following two digits (usually) represent the size of the engine in decilitres, which is the main distinguishing difference. Additional letters or words may be added to the end of the three-digit number to define the fuel type (petrol or diesel), engine or transmission details, and the body style. The \'i\' originally stood for (fuel) \'injection\'.\rThe BMW E28 was the second BMW 5 Series, a stylistic evolution of the E12.\r\rThe following models were sold in Europe:\r    * 518/518i- 1.8 L M10B18\r    * 520i - 2.0 L M20B20 I6\r    524d - 2.4 L M21 diesel I6\r    * 524td - 2.4 L M21 turbodiesel I6\r    * 525i - 2.5 L M30B25 I6\r    * 525e - 2.7 L M20B27 I6\rHigh performance 5 Series - 24-valve DOHC, I6, six throttle bodies, Bosch Motronic integrated fuel injection. At its launch in 1984, the European specification E28 M5 was the fastest production sedan in the world.\r\rVisible changes to this model included revised headlights, Thicker rubber bumper surrounds and large rectangular taillights. The shape was more box shaped than rounded at the rear.\r\rAwards\r\rThe E39 5 Series was on Car and Driver magazine\'s annual Ten Best list for six years straight, from its introduction in 1997 through 2002. It was also Motor Trend\'s Import Car of the Year for 1997 and What Car? Executive Car of the Year 1997 through 2002. The E60 was named "Best New Luxury / Prestige Car" in the 2006 Canadian Car of the Year awards. Active Seat [3] continuous passive motion seating comfort technology recognized as one of the Best Inventions of 1998 by Popular Science magazine. Consumer Reports found the E39 5 series their best car tested in 2001-2002.','','','',215,3,'BMW','525i','1234567',0xFFD8FFE0,41000,'admin',2004,1234567);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `project39_blocking` (`id`,`tablename`,`startdatetime`,`confirmdatetime`,`keys`,`sessionid`,`userid`,`action`) VALUES (17,'carsmodels','2009-10-19 11:14:17','2009-10-19 11:14:17','12','f43h2u4g1g232c6pla44r77ad6','1',1);
INSERT INTO `project39_blocking` (`id`,`tablename`,`startdatetime`,`confirmdatetime`,`keys`,`sessionid`,`userid`,`action`) VALUES (61,'carsmodels','2009-10-19 11:19:55','2009-10-19 11:19:55','4','ll3e73bj0pv7d52stc3kjj8c33','admin',1);
INSERT INTO `project39_blocking` (`id`,`tablename`,`startdatetime`,`confirmdatetime`,`keys`,`sessionid`,`userid`,`action`) VALUES (172,'carsmake','2009-10-20 11:23:01','2009-10-20 11:23:01','1','jbbhp99if6hmqtuqjfoe770e92','admin',1);
INSERT INTO `project39_blocking` (`id`,`tablename`,`startdatetime`,`confirmdatetime`,`keys`,`sessionid`,`userid`,`action`) VALUES (173,'carsmake','2009-10-20 11:23:02','2009-10-20 11:23:02','1','jbbhp99if6hmqtuqjfoe770e92','admin',1);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (33,'2009-10-20 10:54:42','127.0.0.1','Guest','carsusers','login','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (34,'2009-10-20 10:54:45','127.0.0.1','Guest','carsusers','logout','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (35,'2009-10-20 10:54:49','127.0.0.1','','carsusers','failed login','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (37,'2009-10-20 10:55:34','127.0.0.1','Guest','carsusers','login','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (38,'2009-10-20 10:55:43','127.0.0.1','Guest','carsusers','logout','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (39,'2009-10-20 10:55:47','127.0.0.1','Guest','carsusers','login','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (40,'2009-10-20 10:55:56','127.0.0.1','Guest','carsusers','logout','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (41,'2009-10-20 10:56:00','127.0.0.1','','carsusers','logout','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (42,'2009-10-20 10:56:06','127.0.0.1','','carsusers','logout','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (43,'2009-10-20 11:48:05','127.0.0.1','admin','carsusers','logout','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (44,'2009-10-20 11:48:11','127.0.0.1','admin','carsusers','login','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (45,'2009-10-20 11:49:27','127.0.0.1','admin','carsmodels','add','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (46,'2009-10-20 11:49:41','127.0.0.1','admin','carsmake','add','---Keys\r\nid : 16\r\n---Fields\r\nmake [new]: 1\r\n');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (47,'2009-10-20 12:07:38','127.0.0.1','admin','carsmake','delete','---Keys\r\nid : 8\r\n---Fields\r\nmake [old]: Jaguar\r\n');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (48,'2009-10-20 12:09:39','127.0.0.1','admin','carsmodels','delete','');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (49,'2009-10-20 12:09:53','127.0.0.1','admin','carsmake','delete','---Keys\r\nid : 5\r\n---Fields\r\nmake [old]: Subaru\r\n');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (50,'2009-10-20 12:19:10','127.0.0.1','admin','carsmake','delete','---Keys\r\nid : 17\r\n---Fields\r\nmake [old]: 1\r\n');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (51,'2009-10-20 12:19:23','127.0.0.1','admin','carsmodels','delete','---Keys\r\nid : 41\r\n---Fields\r\nmake [old]: 1\r\nmodel [old]: 1\r\n');
INSERT INTO `project41_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (52,'2009-10-20 12:19:23','127.0.0.1','admin','carsmodels','delete','---Keys\r\nid : 42\r\n---Fields\r\nmake [old]: 1\r\nmodel [old]: 1\r\n');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `carsusers` (`id`,`password`,`username`) VALUES (1,'admin','admin');
INSERT INTO `carsusers` (`id`,`password`,`username`) VALUES (2,'user','user');
SET FOREIGN_KEY_CHECKS = 1;
